/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.openideals.greporter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bg=0x7f020000;
        public static final int done=0x7f020001;
        public static final int hourglass=0x7f020002;
        public static final int ic_menu_about=0x7f020003;
        public static final int ic_menu_register=0x7f020004;
        public static final int ic_menu_reports=0x7f020005;
        public static final int icon=0x7f020006;
        public static final int soundbar_mono=0x7f020007;
        public static final int soundbar_plate_mono=0x7f020008;
        public static final int splash=0x7f020009;
        public static final int txt_entry=0x7f02000a;
    }
    public static final class id {
        public static final int btnPlayAudio=0x7f050019;
        public static final int btnRecordAudio=0x7f050018;
        public static final int btnReportFormCancel=0x7f05001b;
        public static final int btnReportFormSubmit=0x7f050015;
        public static final int btnSubmitAudio=0x7f050004;
        public static final int btnSubmitPhoto=0x7f050005;
        public static final int btnSubmitText=0x7f050006;
        public static final int btnTakePicture=0x7f050021;
        public static final int entryCaption=0x7f050023;
        public static final int entryEmail=0x7f050010;
        public static final int entryFirstName=0x7f05000c;
        public static final int entryLastName=0x7f05000e;
        public static final int entryReport=0x7f05001f;
        public static final int entrySubmitUrl=0x7f050012;
        public static final int entryTitle=0x7f05001d;
        public static final int entryViewUrl=0x7f050014;
        public static final int labelAudioStatus=0x7f05001a;
        public static final int labelAudioTitle=0x7f050017;
        public static final int labelCaption=0x7f050022;
        public static final int labelEmail=0x7f05000f;
        public static final int labelFindLocation=0x7f050003;
        public static final int labelFirstName=0x7f05000b;
        public static final int labelIntro=0x7f05000a;
        public static final int labelLastName=0x7f05000d;
        public static final int labelPhotoHeader=0x7f050016;
        public static final int labelPhotoTitle=0x7f050020;
        public static final int labelReport=0x7f05001e;
        public static final int labelSubmitUtl=0x7f050011;
        public static final int labelTitle=0x7f05001c;
        public static final int labelViewUrl=0x7f050013;
        public static final int layoutMapView=0x7f050007;
        public static final int layoutReportForm=0x7f050009;
        public static final int mapview1=0x7f050008;
        public static final int previewphoto=0x7f050024;
        public static final int scrollReportForm=0x7f050002;
        public static final int surface=0x7f050000;
        public static final int webview=0x7f050001;
    }
    public static final class layout {
        public static final int camera=0x7f030000;
        public static final int internalweb=0x7f030001;
        public static final int locator=0x7f030002;
        public static final int main=0x7f030003;
        public static final int map=0x7f030004;
        public static final int personform=0x7f030005;
        public static final int reportaudioform=0x7f030006;
        public static final int reportform=0x7f030007;
        public static final int reportphotoform=0x7f030008;
        public static final int splash=0x7f030009;
        public static final int view=0x7f03000a;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int geo_map_view=0x7f040007;
        public static final int hello=0x7f040001;
        public static final int internal_camera_view=0x7f040009;
        public static final int internal_web_view=0x7f040006;
        public static final int splash_msg=0x7f040008;
        public static final int view_audio_form=0x7f040004;
        public static final int view_location_finder=0x7f040002;
        public static final int view_photo_form=0x7f040005;
        public static final int view_report_form=0x7f040003;
    }
}
